export const mockUser = {
  id: 'user-1',
  full_name: 'ינון נפתלי',
  first_name: 'ינון',
  last_name: 'נפתלי',
  email: 'ynon@example.com',
  country: 'ניו זילנד',
  country_flag: '🇳🇿',
  city: 'אוקלנד',
  bio: 'שף חובב שמבשל ישראלי בניו זילנד. מתמחה בפיוז\'ן ים תיכוני.',
  recipes_count: 12,
  shared_count: 8,
  likes_count: 247,
  saved_count: 34,
}

export const CATEGORY_GRADIENTS = {
  'ממרחים':       'linear-gradient(160deg, #1e3a6e 0%, #3d6fa8 100%)',
  'ארוחת בוקר':  'linear-gradient(160deg, #7c1d1d 0%, #c0392b 100%)',
  'סלטים':        'linear-gradient(160deg, #1a4731 0%, #27ae60 100%)',
  'קינוחים':      'linear-gradient(160deg, #3d2914 0%, #8b5e3c 100%)',
  'בשרי':         'linear-gradient(160deg, #4a1010 0%, #8b2020 100%)',
  'טבעוני':       'linear-gradient(160deg, #1a3d1a 0%, #3cb371 100%)',
  'מרקים':        'linear-gradient(160deg, #2d1a4a 0%, #7b52ab 100%)',
}

export const mockRecipes = [
  {
    id: 'r1',
    image_url: 'https://images.unsplash.com/photo-1637949385162-e416fb15b2ce?w=800&q=80',
    title: 'חומוס ביתי',
    description: 'חומוס קרמי ועשיר כמו של אמא — מושלם לארוחת ערב ישראלית בלב ברלין.',
    category: 'ממרחים',
    country_origin: 'ישראל',
    prep_time: 20,
    cook_time: 40,
    servings: 6,
    level: 'קל',
    is_public: true,
    users: { full_name: 'מיכל כהן', country: 'גרמניה', country_flag: '🇩🇪', city: 'ברלין' },
    likes_count: 42,
    comments_count: 8,
    ingredients: [
      { id: 'i1', name_he: 'גרגירי חומוס', name_local: 'Chickpeas', quantity: '2', unit: 'כוסות', is_rare: false },
      { id: 'i2', name_he: 'טחינה', name_local: 'Tahini', quantity: '4', unit: 'כפות', is_rare: false },
      { id: 'i3', name_he: 'שמן זית', name_local: 'Olive oil', quantity: '3', unit: 'כפות', is_rare: false },
      { id: 'i4', name_he: 'לימון', name_local: 'Lemon', quantity: '1', unit: 'יחידה', is_rare: false },
      { id: 'i5', name_he: 'שום', name_local: 'Garlic', quantity: '2', unit: 'שיני', is_rare: false },
    ],
    steps: [
      { step_number: 1, description: 'השרו את גרגירי החומוס במים ללילה שלם', duration_seconds: null },
      { step_number: 2, description: 'בשלו את החומוס במים רותחים עד לריכוך מלא, כ-40 דקות', duration_seconds: 2400 },
      { step_number: 3, description: 'טחנו יחד חומוס, טחינה, שום, לימון ושמן זית עד לקבלת מרקם חלק', duration_seconds: null },
      { step_number: 4, description: 'הוסיפו מלח לפי הטעם', duration_seconds: null },
      { step_number: 5, description: 'הגישו עם שמן זית, פפריקה ופטרוזיליה קצוצה', duration_seconds: null },
    ],
    source_url: null,
  },
  {
    id: 'r2',
    image_url: 'https://images.unsplash.com/photo-1614570218825-c2a3be79b0fd?w=800&q=80',
    title: 'שקשוקה קלאסית',
    description: 'ביצים ברוטב עגבניות ופלפלים — ארוחת בוקר ישראלית שכובשת את ניו יורק.',
    category: 'ארוחת בוקר',
    country_origin: 'ישראל',
    prep_time: 10,
    cook_time: 20,
    servings: 2,
    level: 'קל',
    is_public: true,
    users: { full_name: 'יוני לוי', country: 'ארה"ב', country_flag: '🇺🇸', city: 'ניו יורק' },
    likes_count: 89,
    comments_count: 15,
    ingredients: [
      { id: 'i6', name_he: 'עגבניות', name_local: 'Tomatoes', quantity: '4', unit: 'יחידות', is_rare: false },
      { id: 'i7', name_he: 'פלפל אדום', name_local: 'Red bell pepper', quantity: '1', unit: 'יחידה', is_rare: false },
      { id: 'i8', name_he: 'ביצים', name_local: 'Eggs', quantity: '4', unit: 'יחידות', is_rare: false },
      { id: 'i9', name_he: 'שמן זית', name_local: 'Olive oil', quantity: '2', unit: 'כפות', is_rare: false },
      { id: 'i10', name_he: 'כמון', name_local: 'Cumin', quantity: '1', unit: 'כפית', is_rare: false },
      { id: 'i11', name_he: 'פפריקה מעושנת', name_local: 'Smoked paprika', quantity: '1', unit: 'כפית', is_rare: false },
    ],
    steps: [
      { step_number: 1, description: 'חממו שמן זית במחבת רחבה על אש בינונית', duration_seconds: null },
      { step_number: 2, description: 'טגנו בצל וגרגרי שום עד להשחמה קלה', duration_seconds: 300 },
      { step_number: 3, description: 'הוסיפו פלפל, כמון ופפריקה ובשלו 2 דקות', duration_seconds: 120 },
      { step_number: 4, description: 'הוסיפו עגבניות מרוסקות ובשלו 10 דקות עד להסמכה', duration_seconds: 600 },
      { step_number: 5, description: 'שברו ביצים לתוך הרוטב וכסו עד לקבלת מרקם רצוי', duration_seconds: 300 },
    ],
    source_url: null,
  },
  {
    id: 'r3',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    title: 'סלט ישראלי',
    description: 'עגבניות, מלפפון, בצל וגרגיר הנחלים — פריז לא ידעה סלט כזה.',
    category: 'סלטים',
    country_origin: 'ישראל',
    prep_time: 15,
    cook_time: 0,
    servings: 4,
    level: 'קל',
    is_public: true,
    users: { full_name: 'דנה מזרחי', country: 'צרפת', country_flag: '🇫🇷', city: 'פריז' },
    likes_count: 56,
    comments_count: 12,
    ingredients: [
      { id: 'i12', name_he: 'עגבניות', name_local: 'Tomatoes', quantity: '3', unit: 'יחידות', is_rare: false },
      { id: 'i13', name_he: 'מלפפון', name_local: 'Cucumber', quantity: '2', unit: 'יחידות', is_rare: false },
      { id: 'i14', name_he: 'בצל סגול', name_local: 'Red onion', quantity: '0.5', unit: 'יחידה', is_rare: false },
      { id: 'i15', name_he: 'גרגיר נחלים', name_local: 'Watercress', quantity: '1', unit: 'צרור', is_rare: true, where_to_buy: 'Metro, Monoprix — קטגוריית ירקות' },
      { id: 'i16', name_he: 'שמן זית', name_local: 'Olive oil', quantity: '3', unit: 'כפות', is_rare: false },
      { id: 'i17', name_he: 'לימון', name_local: 'Lemon', quantity: '1', unit: 'יחידה', is_rare: false },
    ],
    steps: [
      { step_number: 1, description: 'חתכו עגבניות, מלפפון ובצל לקוביות קטנות', duration_seconds: null },
      { step_number: 2, description: 'ערבבו עם גרגיר הנחלים', duration_seconds: null },
      { step_number: 3, description: 'תבלו בשמן זית, לימון, מלח ופלפל', duration_seconds: null },
      { step_number: 4, description: 'הגישו מיד', duration_seconds: null },
    ],
    source_url: null,
  },
  {
    id: 'r4',
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80',
    title: 'ביסקוטי תפוז ואניס',
    description: 'עוגיות קשות ופריכות לטבילה בקפה — המתכון הסודי של סבתא.',
    category: 'קינוחים',
    prep_time: 30,
    cook_time: 50,
    servings: 24,
    level: 'בינוני',
    is_public: true,
    users: { full_name: 'ינון נפתלי', country: 'ניו זילנד', country_flag: '🇳🇿', city: 'אוקלנד' },
    likes_count: 73,
    comments_count: 21,
    ingredients: [
      { id: 'i18', name_he: 'קמח', name_local: 'Flour', quantity: '2', unit: 'כוסות', is_rare: false },
      { id: 'i19', name_he: 'סוכר', name_local: 'Sugar', quantity: '1', unit: 'כוס', is_rare: false },
      { id: 'i20', name_he: 'ביצים', name_local: 'Eggs', quantity: '3', unit: 'יחידות', is_rare: false },
      { id: 'i21', name_he: 'אניס', name_local: 'Anise seeds', quantity: '1', unit: 'כפית', is_rare: true, where_to_buy: 'חנויות תבלינים אתניות, Amazon' },
    ],
    steps: [
      { step_number: 1, description: 'ערבבו קמח, סוכר, אניס ואבקת אפייה', duration_seconds: null },
      { step_number: 2, description: 'הוסיפו ביצים, שמן ומיץ תפוז ולושו עד לבצק אחיד', duration_seconds: null },
      { step_number: 3, description: 'צרו כיכרות ארוכות ואפו ב-180° למשך 25 דקות', duration_seconds: 1500 },
      { step_number: 4, description: 'חתכו לפרוסות ואפו עוד 15 דקות מכל צד', duration_seconds: 900 },
    ],
    source_url: null,
  },
]

export const mockCommunities = [
  { id: 'c1', country_code: 'US', country_name: 'ארה"ב',     country_flag: '🇺🇸', member_count: 1247, recipes_count: 342, lat: 39.8,  lng: -98.5,  is_mine: false },
  { id: 'c2', country_code: 'DE', country_name: 'גרמניה',    country_flag: '🇩🇪', member_count: 892,  recipes_count: 218, lat: 51.2,  lng: 10.4,   is_mine: false },
  { id: 'c3', country_code: 'GB', country_name: 'בריטניה',   country_flag: '🇬🇧', member_count: 756,  recipes_count: 189, lat: 52.4,  lng: -1.5,   is_mine: false },
  { id: 'c4', country_code: 'FR', country_name: 'צרפת',      country_flag: '🇫🇷', member_count: 623,  recipes_count: 156, lat: 46.2,  lng: 2.2,    is_mine: false },
  { id: 'c5', country_code: 'AU', country_name: 'אוסטרליה',  country_flag: '🇦🇺', member_count: 445,  recipes_count: 112, lat: -25.3, lng: 133.8,  is_mine: false },
  { id: 'c6', country_code: 'CA', country_name: 'קנדה',      country_flag: '🇨🇦', member_count: 398,  recipes_count: 98,  lat: 56.1,  lng: -106.3, is_mine: false },
  { id: 'c7', country_code: 'NL', country_name: 'הולנד',     country_flag: '🇳🇱', member_count: 287,  recipes_count: 72,  lat: 52.1,  lng: 5.3,    is_mine: false },
  { id: 'c8', country_code: 'NZ', country_name: 'ניו זילנד', country_flag: '🇳🇿', member_count: 156,  recipes_count: 43,  lat: -40.9, lng: 174.9,  is_mine: true },
]

export const COUNTRIES = [
  'אוזבקיסטן', 'אוסטרליה', 'אוסטריה', 'אוקראינה', 'איטליה', 'אירלנד', 'איסלנד',
  'אמירויות הערביות', 'אנגולה', 'ארגנטינה', 'ארה"ב',
  'בולגריה', 'בלגיה', 'בריטניה', 'ברזיל',
  'גרמניה', 'גיאורגיה',
  'דנמרק', 'דרום אפריקה', 'דרום קוריאה',
  'הודו', 'הולנד', 'הונגריה',
  'יוון', 'יפן',
  'לוקסמבורג',
  'מלטה', 'מקסיקו', 'מרוקו',
  'ניו זילנד', 'נורווגיה',
  'סינגפור', 'סלובניה', 'ספרד', 'סרביה',
  'פולין', 'פינלנד', 'פורטוגל', 'פנמה', 'פרו',
  "צ'כיה", "צ'ילה", 'צרפת',
  'קולומביה', 'קנדה', 'קפריסין', 'קרואטיה',
  'רומניה', 'רוסיה',
  'שוויץ', 'שוודיה',
  'תאילנד', 'תורכיה',
]
